### ISSUE TITLE
Split legacy-support-v4 module into corresponding non-legacy modules

### ISSUE THREAD

**Issue by erikghonyan** [pkware/truth-android#24]

**Comment by erikghonyan** [comment]
@MariusVolkhart do you think it's better to include this in 2.0.0? Just not to have anything legacy and not to introduce another breaking change later

**Comment by MariusVolkhart** [comment]
Yes, i think that'd be good. (was out on holiday, hence the late reply)

**Comment by erikghonyan** [comment]
Sounds great! I'll draft something soon
