### ISSUE TITLE
Release 2.0.0

### ISSUE THREAD

**Issue by erikghonyan** [pkware/truth-android#29]

**Comment by erikghonyan** [comment]
@MariusVolkhart is there anything left to be done for this release?

**Comment by MariusVolkhart** [comment]
No, thanks for the reminder. I'll get it done this week

**Comment by erikghonyan** [comment]
Thank you! 🎉

**Comment by MariusVolkhart** [comment]
`2.0.0` is available in maven central. @erikghonyan thanks again for all the contributions!
